PUT http://localhost:3000/alumnos/actualizar/41
Content-Type: application/json

{
    "nombres": "Juan Carlos",
    "apellidos": "Velazquez",
    "username": "jcvelazquez",
    "dni": 30258741,
    "email": "nuevoemail@ejemplo.com",
    "password": "123456789"
}
